version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  path-filtering: circleci/path-filtering@0.0.2

jobs:
  generate_continuation_config:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - path-filtering/set-parameters:
          mapping: |
            src/.*.ftl build-code true
          base-revision: master
          # Output the json object created in mapping to path_flags.json
          output-path: path_flags.json

      - run:
          name: What's in the path_flags.json?
          command: |
            echo $(cat path_flags.json | jq)

      - run:
          name: What's inside the src/profile/common/locales/it-IT/common.ftl?
          command: |
            echo $(cat src/profile/common/locales/it-IT/common.ftl)
            mv src/profile/common/locales/it-IT/common.ftl src/profile/common/locales/test/common.ft 
            echo $(cat src/profile/common/locales/test/common.ft)

workflows:
  setup-workflow:
    jobs:
      - generate_continuation_config
